# We can have different configuration files(based on environment as well) or the properties defined in a single file as well depending on the preference
# This is prospective STAGE environment profile